### ISSUE TITLE
Discrepancy in model training results

### ISSUE THREAD

**Issue by idchacon28** [Alexandre-Delplanque/HerdNet#13]
Hello Alexandre,  
  
I have been attempting to reproduce the training results for the HerdNet model as described in your repository, but I am encountering some discrepancies in the outcomes. I have followed the instructions and used the `tools/patcher.py` script to obtain training patches from the HERDNET dataset. I made sure to select patches with at least one animal, with a patch height and width of 512 and an overlap of 160 pixels, and kept the down_ratio at 2.  
  
I have also defined seven classes for the model, including the 'background' class, and adjusted the weight tensor for the loss accordingly (`weight = Tensor([0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0])`).  
  
Below is the training script I have utilized:

```
import os
import sys 
from animaloc.utils.seed import set_seed
import albumentations as A
from animaloc.datasets import CSVDataset
from animaloc.data.transforms import MultiTransformsWrapper, DownSample, PointsToMask, FIDT
from torch.utils.data import DataLoader
from animaloc.models import HerdNet, LossWrapper, load_model
from torch import Tensor
from animaloc.train.losses import FocalLoss
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from animaloc.train import Trainer
from animaloc.eval import PointsMetrics, HerdNetStitcher, HerdNetEvaluator
import torch
import wandb

set_seed(9292)

patch_size = 512
num_classes = 7 # 7 classes: 'buffalo', 'elephant', 'kob','topi','warthog','waterbuck', and background.
down_ratio = 2
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
work_dir = './herdnet_training' # output directory
os.makedirs(work_dir, exist_ok=True)
root_dir = '~/train_patches_and_csv' # generated by tools/patcher.py
train_dataset = CSVDataset(
    csv_file = os.path.join(root_dir, 'gt.csv'), #gt.csv generated by tools/patcher.py
    root_dir = root_dir,
    albu_transforms = [
        A.VerticalFlip(p=0.5),
        A.HorizontalFlip(p=0.5),
        A.RandomRotate90(p=0.5),
        A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.2),
        A.Blur(blur_limit=15, p=0.2),     
        A.Normalize(p=1.0)
        ],
    end_transforms = [MultiTransformsWrapper([
        FIDT(num_classes=num_classes, down_ratio=down_ratio),
        PointsToMask(radius=2, num_classes=num_classes, squeeze=True, down_ratio=int(patch_size//16))
        ])]
    )

val_dataset = CSVDataset(
    csv_file = '/herdnet_general/general_dataset/groundtruth/csv/test_big_size_A_B_E_K_WH_WB_herdnet_format_right_labels.csv',
    root_dir = '/herdnet_general/general_dataset/test',
    albu_transforms = [A.Normalize(p=1.0)],
    end_transforms = [DownSample(down_ratio=down_ratio, anno_type='point')]
    )

train_dataloader = DataLoader(
    dataset = train_dataset,
    batch_size = 32,
    shuffle = True
    )

val_dataloader = DataLoader(
    dataset = val_dataset,
    batch_size = 1,
    shuffle = False
    )

herdnet = HerdNet(num_classes=num_classes, down_ratio=down_ratio).to(device)
weight = Tensor([0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]).to(device) # herdnet weights

losses = [
    {'loss': FocalLoss(reduction='mean', normalize=False), 'idx': 0, 'idy': 0, 'lambda': 1.0, 'name': 'focal_loss'},
    {'loss': CrossEntropyLoss(reduction='mean', weight=weight), 'idx': 1, 'idy': 1, 'lambda': 1.0, 'name': 'ce_loss'}
    ]

herdnet = LossWrapper(herdnet, losses=losses)
lr = 1e-4
weight_decay = 1e-3
epochs = 100

optimizer = Adam(params=herdnet.parameters(), lr=lr, weight_decay=weight_decay)
metrics = PointsMetrics(radius=20, num_classes=num_classes) # radius for herdnet data

stitcher = HerdNetStitcher(
    model=herdnet, 
    size=(patch_size,patch_size), 
    overlap=160, 
    down_ratio=down_ratio, 
    reduction='mean'
    )

evaluator = HerdNetEvaluator(
    model=herdnet, 
    dataloader=val_dataloader, 
    metrics=metrics, 
    stitcher=stitcher, 
    work_dir=work_dir, 
    header='validation'
    )

trainer = Trainer(
    model=herdnet,
    train_dataloader=train_dataloader,
    optimizer=optimizer,
    num_epochs=epochs,
    evaluator=evaluator,
    work_dir=work_dir
    )
wandb.init(project='herdnet')
trainer.start(warmup_iters=100, checkpoints='best', select='max', validate_on='f1_score', wandb_flag=False)
```
  
With this setup, I have tested your pre-trained weights and could replicate your results. However, the model I have trained only achieves an f1 score of 0.63, as opposed to the 0.83 score reported in your results.  
  
I am wondering if this difference may be due to the Hard negative patch mining technique mentioned in your paper, which I could not find an implementation of in the repository. Could this be the reason for the discrepancy, or is there something else I might be missing?  
  
I am attaching the results image of my training for your reference: 

![Image](https://github.com/user-attachments/assets/2845bda1-7560-4bbe-88b7-f3f5abf980df)

  
I would greatly appreciate any guidance or suggestions you could provide to help me achieve the expected training results.  
  
Thank you for your time and assistance.  
  
Best regards,  
Daniel C

**Comment by Alexandre-Delplanque** [comment]
Hi @idchacon28,

Thanks for opening this issue.

I think the difference is definitely due to the use of HNP mining, which considerably reduces false positives while maintaining a high recall, and therefore increases the F1 score.

Here's the configuration files I used at the time to train the model. I quickly noticed that the batch size was not the same, for example:
```yaml
wandb_project: YOURS # to change
wandb_entity: YOURS # to change
seed: 9292
device_name: cuda
model:
  name: HerdNet
  load_from: null
  resume_from: null
  kwargs:
    num_layers: 34
    pretrained: true
    down_ratio: 2
    head_conv: 64
losses:
  FocalLoss:
    print_name: focal_loss
    from_torch: false
    output_idx: 0
    target_idx: 0
    lambda_const: 1.0
    kwargs:
      reduction: mean
      normalize: false
  CrossEntropyLoss:
    print_name: CE_loss
    from_torch: true
    output_idx: 1
    target_idx: 1
    lambda_const: 1.0
    kwargs:
      reduction: mean
      weight: [0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]
datasets:
  img_size: [512,512]
  anno_type: point
  num_classes: 7
  collate_fn: null
  train:
    name: CSVDataset
    csv_file: D:/Alexandre/data/train/patches/gt.csv
    root_dir: D:/Alexandre/data/train/patches
    sample_on: null
    albu_transforms:
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.2
      Blur:
        blur_limit: 15
        p: 0.2
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      MultiTransformsWrapper:
        FIDT:
          num_classes: 2
          add_bg: false
          down_ratio: ${train.model.kwargs.down_ratio}
        PointsToMask:
          radius: 2
          num_classes: ${train.datasets.num_classes}
          squeeze: true
          down_ratio: 32
  validate:
    name: CSVDataset
    csv_file: D:/Alexandre/data/val/patches/gt.csv
    root_dir: D:/Alexandre/data/val/patches
    albu_transforms:
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      DownSample:
        down_ratio: ${train.model.kwargs.down_ratio}
        anno_type: ${train.datasets.anno_type}
training_settings:
  trainer: Trainer
  print_freq: 100
  batch_size: 4
  optimizer: adam
  lr: 0.0001
  weight_decay: 0.0005
  auto_lr:
    mode: max
    patience: 10
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 10
    min_lr: 1.0e-06
    verbose: true
  warmup_iters: 100
  epochs: 100
  evaluator:
    name: HerdNetEvaluator
    threshold: 5
    select_mode: max
    validate_on: f1_score
    kwargs:
      print_freq: 10
      lmds_kwargs:
        kernel_size: [3,3]
        adapt_ts: 0.3
  stitcher:
    name: HerdNetStitcher
    kwargs:
      overlap: 160
      down_ratio: ${train.model.kwargs.down_ratio}
      up: false
      reduction: mean
```

To generate HNPs, after the first training session, you'll need to run the best model on the fullsize training images to collect detections (you can use [`infer.py`](https://github.com/Alexandre-Delplanque/HerdNet/blob/v0.1.0/tools/infer.py) for example), then use [`patcher.py`](https://github.com/Alexandre-Delplanque/HerdNet/blob/v0.1.0/tools/patcher.py) to obtain patches with detections, and finally merge this patches folder with the one with the ground truth patches. Be sure to use the `gt.csv` containing the ground truths and not the one with the model detections (flooded with false positives). You can then use the second configuration file for the second training stage:
```yaml
wandb_project: YOURS # to change
wandb_entity: YOURS # to change
seed: 9292
device_name: cuda
model:
  name: HerdNet
  load_from: PATH/TO/PTH/1 # to change
  resume_from: null
  kwargs:
    num_layers: 34
    pretrained: true
    down_ratio: 2
    head_conv: 64
losses:
  FocalLoss:
    print_name: focal_loss
    from_torch: false
    output_idx: 0
    target_idx: 0
    lambda_const: 1.0
    kwargs:
      reduction: mean
      normalize: false
  CrossEntropyLoss:
    print_name: CE_loss
    from_torch: true
    output_idx: 1
    target_idx: 1
    lambda_const: 1.0
    kwargs:
      reduction: mean
      weight: [0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]
datasets:
  img_size: [512, 512]
  anno_type: point
  num_classes: 7
  collate_fn: null
  train:
    name: FolderDataset # changed compare to train session 1
    csv_file: D:/Alexandre/data/train/patches/gt.csv
    root_dir: D:/Alexandre/data/train/hnps
    sample_on: null
    albu_transforms:
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.2
      Blur:
        blur_limit: 15
        p: 0.2
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      MultiTransformsWrapper:
        FIDT:
          num_classes: ${train.datasets.num_classes}
          add_bg: false
          down_ratio: ${train.model.kwargs.down_ratio}
        PointsToMask:
          radius: 2
          num_classes: ${train.datasets.num_classes}
          squeeze: true
          down_ratio: 32
  validate:
    name: CSVDataset
    csv_file: D:/Alexandre/data/val.csv # changed compare to train session 1
    root_dir: D:/Alexandre/data/val/full # changed compare to train session 1
    albu_transforms:
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      DownSample:
        down_ratio: ${train.model.kwargs.down_ratio}
        anno_type: ${train.datasets.anno_type}
training_settings:
  trainer: Trainer
  print_freq: 100
  batch_size: 4
  optimizer: adam
  lr: 1.0e-06 # changed compare to train session 1
  weight_decay: 0.0005
  auto_lr:
    mode: max
    patience: 10
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 10
    min_lr: 1.0e-06
    verbose: true
  warmup_iters: 1
  epochs: 50 # changed compare to train session 1
  evaluator:
    name: HerdNetEvaluator
    threshold: 5
    select_mode: max
    validate_on: f1_score
    kwargs:
      print_freq: 10
      lmds_kwargs:
        kernel_size: [3,3]
        adapt_ts: 0.3
  stitcher:
    name: HerdNetStitcher
    kwargs:
      overlap: 160 # changed compare to train session 1
      down_ratio: ${train.model.kwargs.down_ratio}
      up: false
      reduction: mean
```

I'll let you try this out and get back to me if you still observe significant differences. Do not forget to use the [v0.1.0](https://github.com/Alexandre-Delplanque/HerdNet/tree/v0.1.0)!

Hope this helps!

Best,

Alexandre

**Comment by idchacon28** [comment]
Dear Alexandre,

Thanks for your response.

Firstly, I noticed that in the configuration files you provided, there's a different folder specified for validation during the second training phase compared to the first. Could you explain the reasoning behind using a separate validation folder? 

Secondly, I also noticed you modified the 'train' 'name' value from 'CSVDataset' to 'FolderDataset' in the second config file. Could you clarify why is this modification necessary? 

In the config you mentioned in the kwargs of the stitcher the following: "overlap: 160 # changed compare to train session 1.". However, I see this value is the same for the first training session. Is this value the same in both training sessions?

Also, I would like to understand the criteria used to define a "hard" negative example. Is there a particular threshold involved in determining whether a false positive is considered "hard"? If so, what threshold value do you recommend using for this purpose?

Lastly, I'm a bit uncertain about how to label and record the hard negative examples in the .csv file, especially for patches that contain false positives but no actual animals. Could you provide guidance on what label should be assigned to these patches and how their location should be documented in the .csv file?

I would greatly appreciate your insights into these questions, as they will help me to better understand and implement the HNP mining technique to achieve the expected training results.

Thank you for your time and assistance. Looking forward to your response.

Best,
Daniel C

**Comment by Alexandre-Delplanque** [comment]
Hi @idchacon28,

Please find my responses to each of your question below:

> Firstly, I noticed that in the configuration files you provided, there's a different folder specified for validation during the second training phase compared to the first. Could you explain the reasoning behind using a separate validation folder?

As indicated in section 3.3.2 (“Model training”) of the paper, HerdNet was validated on patches during the first training session and then on 24MP images for the second training session. Please reread this section for further details. The reason for this was to speed up the model training process and avoid validating on 24MP images during the first training phase

> Secondly, I also noticed you modified the 'train' 'name' value from 'CSVDataset' to 'FolderDataset' in the second config file. Could you clarify why is this modification necessary?

The [FolderDataset ](https://github.com/Alexandre-Delplanque/HerdNet/blob/f6586a1bf846cf6ac66762ad84091e3476e1e435/animaloc/datasets/folder.py#L30)lets you load patches without annotations for model training. It reads all the images in a folder and treats all images without annotations in the CSV file as negative (i.e. without animals), returning them with “empty” targets. You need this to load the HNPs.

> In the config you mentioned in the kwargs of the stitcher the following: "overlap: 160 # changed compare to train session 1.". However, I see this value is the same for the first training session. Is this value the same in both training sessions?

Sorry, my mistake. Overlap is set to 0 for validation on patches (no need for overlap since the window is 512x512px).

> Also, I would like to understand the criteria used to define a "hard" negative example. Is there a particular threshold involved in determining whether a false positive is considered "hard"? If so, what threshold value do you recommend using for this purpose?

You could use score thresholding if you wish. For my part, I kept all detections unthresholded on the scores, but thresholded on the location map values according to an adaptive threshold of 0.3, as indicated in the configuration file (`adapt_ts=0.3`).

> Lastly, I'm a bit uncertain about how to label and record the hard negative examples in the .csv file, especially for patches that contain false positives but no actual animals. Could you provide guidance on what label should be assigned to these patches and how their location should be documented in the .csv file?

No need to enter HNPs in the CSV file, as FolderDataset is used (see above). Using [`patcher.py`](https://github.com/Alexandre-Delplanque/HerdNet/blob/v0.1.0/tools/patcher.py) on the model detections, as recommended above, you'll get all the patches with false positives in one folder, then just merge the images with the folder containing the positive patches, and finally use the CSV containing only the annotated animals as gt. The FolderDataset will handle the task of determining which patches are negative and which are positive with annotations, but will send both back to the model during training.

Hope this helps!

Cheers

Alexandre

**Comment by idchacon28** [comment]
Hi @Alexandre-Delplanque,

Thank you so much for your detailed response to my questions. I followed your guidance and was able to successfully replicate the results when training from scratch on the HerdNet general dataset! I really appreciate your help in clarifying the process for me.

I've attached a photo of the metrics I obtained, which align closely with those reported in this repository. 

![Image](https://github.com/user-attachments/assets/2b0b215e-440a-46a7-994e-909d9d14fefd)

Thanks again for your support!

Best regards,
Daniel

**Comment by Alexandre-Delplanque** [comment]
Hi @idchacon28 ,

Great! Glad I could help.

Would you mind sharing your config files?

Then I'll close the issue.

Best,

Alexandre

**Comment by idchacon28** [comment]
For sure! For the firs training stage I used the python script I put when opening the issue. Then I used the best model based on f1-score to obtain detections (including false positives). I merged those patches (using patcher.py) with the original dataset while keeping the original csv with the right grounddtruths. Then I started training for the second stage using the merged dataset and the following config file:
``` 
wandb_project: 'wandb_project' # to change
wandb_entity: 'wandb_entity' # to change
wandb_run: 'wandb_run' # to change
seed: 9292
device_name: cuda
model:
  name: HerdNet
  from_torchvision: False
  load_from: '~/best_model.pth' # to change
  resume_from: null
  kwargs:
    num_layers: 34
    pretrained: true
    down_ratio: 2
    head_conv: 64
  freeze: null
losses:
  FocalLoss:
    print_name: focal_loss
    from_torch: false
    output_idx: 0
    target_idx: 0
    lambda_const: 1.0
    kwargs:
      reduction: mean
      normalize: false
  CrossEntropyLoss:
    print_name: CE_loss
    from_torch: true
    output_idx: 1
    target_idx: 1
    lambda_const: 1.0
    kwargs:
      reduction: mean
      weight: [0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]
datasets:
  img_size: [512, 512]
  anno_type: point
  num_classes: 7
  collate_fn: null
  
  class_def:
    0: 'background'
    1: 'class1'
    2: 'class2'
    3: 'class3'
    4: 'class4'
    5: 'class5'
    6: 'class6'
  train:
    name: FolderDataset # changed compare to train session 1
    csv_file: '~/herdnet_general/general_dataset/merged_training_fps_patches/gt.csv'
    root_dir: '~/herdnet_general/general_dataset/merged_training_fps_patches'
    sampler: null
    albu_transforms:
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.2
      Blur:
        blur_limit: 15
        p: 0.2
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      MultiTransformsWrapper:
        FIDT:
          num_classes: ${train.datasets.num_classes}
          add_bg: false
          down_ratio: ${train.model.kwargs.down_ratio}
        PointsToMask:
          radius: 2
          num_classes: ${train.datasets.num_classes}
          squeeze: true
          down_ratio: 32
  validate:
    name: CSVDataset
    csv_file: '~/herdnet_general/general_dataset/groundtruth/csv/test_big_size_A_B_E_K_WH_WB_herdnet_format_right_labels.csv'
    root_dir: '~/herdnet_general/general_dataset/test' 
    albu_transforms:
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      DownSample:
        down_ratio: ${train.model.kwargs.down_ratio}
        anno_type: ${train.datasets.anno_type}
training_settings:
  valid_freq: 1
  trainer: Trainer
  print_freq: 100
  batch_size: 32
  optimizer: adam
  lr: 1.0e-06 # changed compare to train session 1
  weight_decay: 0.0005
  auto_lr:
    mode: max
    patience: 10
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 10
    min_lr: 1.0e-06
    verbose: true
  warmup_iters: 1
  vizual_fn: null
  epochs: 50 # changed compare to train session 1
  evaluator:
    name: HerdNetEvaluator
    threshold: 20
    select_mode: max
    validate_on: f1_score
    kwargs:
      print_freq: 10
      lmds_kwargs:
        kernel_size: [3,3]
        adapt_ts: 0.3
  stitcher:
    name: HerdNetStitcher
    kwargs:
      overlap: 160 # changed compare to train session 1
      down_ratio: ${train.model.kwargs.down_ratio}
      up: false
      reduction: mean
```
It is worth noting I used a higher batch size (32 vs 4) compared to your config file. Also, I used the main branch instead of v0.1.0, which is why some entries in the config are slightly different to yours (for example you use 'sample_on=None' and I use 'sampler=None').
Finally, I used the following config for testing:
``` 
wandb_project: 'Sample project'
wandb_entity: 'youraccountname'
wandb_run: 'myrun'
device_name: 'cuda'

model: 
  name: 'HerdNet'
  from_torchvision: False
  pth_file: '~/HerdNet/outputs/2025-03-20/22-35-25/best_model.pth' # the final model
  kwargs:
    num_layers: 34
    pretrained: False
    down_ratio: 2
    head_conv: 64

dataset:
  img_size: [512,512]
  anno_type: 'point'
  num_classes: 7
  collate_fn: null

  class_def:
    1: 'buffalo'
    2: 'elephant'
    3: 'kob'
    4: 'topi'
    5: 'warthog'
    6: 'waterbuck'

  name: 'CSVDataset'
  csv_file: '~/herdnet_general/general_dataset/groundtruth/csv/test_big_size_A_B_E_K_WH_WB_herdnet_format_right_labels.csv' # images, x,y,labels format
  root_dir: '~/herdnet_general/general_dataset/test'

  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

evaluator:
  name: 'HerdNetEvaluator'
  threshold: 20
  kwargs:
    lmds_kwargs:
      kernel_size: [3,3]
      adapt_ts: 0.3

stitcher:
  name: 'HerdNetStitcher'
  kwargs:
    overlap: 160
    down_ratio: ${test.model.kwargs.down_ratio}
    up: False
    reduction: 'mean'
```

Greetings!
Daniel
